import { useRef } from 'react';
import { Clock3, Star, Trash2, Download, Upload, ArrowUpRight } from 'lucide-react';
import type { HistoryItem } from '../types/qr';
export default function HistoryStrip({ items, select, togglePin, remove, clear, exportAll, importAll, notice }: { items: HistoryItem[]; select: (item: HistoryItem) => void; togglePin: (id: string) => void; remove: (id: string) => void; clear: () => void; exportAll: () => void; importAll: (file: File) => void; notice: (text: string) => void }) {
  const file = useRef<HTMLInputElement>(null);
  return <section className="history-section"><div className="history-head"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Recent creations <span className="history-count">{items.length}</span></h2><p>Your codes stay right here, in your browser.</p></div><div className="history-actions"><input type="file" className="sr-only" ref={file} accept="application/json,.json" aria-label="Import history JSON" onChange={e => { const chosen = e.target.files?.[0]; if (chosen) importAll(chosen); e.target.value = ''; }}/><button type="button" onClick={() => file.current?.click()} title="Import saved QR history"><Upload size={15}/> Import</button><button type="button" onClick={exportAll} disabled={!items.length} title="Download history backup as JSON"><Download size={15}/> Export</button><button type="button" onClick={() => { if (items.length && window.confirm('Delete all recent QRs, including favourites?')) { clear(); notice('History cleared'); } }} disabled={!items.length} title="Clear all recent QRs"><Trash2 size={15}/> Clear</button></div></div>
    {items.length ? <div className="history-list">{items.map(item => <div className="history-item" key={item.id}><button type="button" className="history-open" onClick={() => select(item)} title="Load this QR into the editor"><span className="history-thumb" style={{ background: item.settings.background }}><span style={{ color: item.settings.foreground }}>▦</span></span><span className="history-text"><strong>{item.type === 'vcard' ? 'vCard' : item.type === 'wifi' ? 'Wi-Fi' : item.type.charAt(0).toUpperCase() + item.type.slice(1)}</strong><small>{item.preview || 'Untitled QR'}</small></span><ArrowUpRight size={15}/></button><div className="history-item-actions"><button type="button" onClick={() => togglePin(item.id)} title={item.pinned ? 'Unpin favourite' : 'Pin as favourite'} aria-label={item.pinned ? 'Unpin favourite' : 'Pin as favourite'}><Star size={16} fill={item.pinned ? 'currentColor' : 'none'}/></button><button type="button" onClick={() => remove(item.id)} title="Delete QR" aria-label="Delete QR"><Trash2 size={16}/></button></div></div>)}</div> : <div className="empty-history"><Clock3 size={22}/><span>Your generated codes will appear here. Create something above to get started.</span></div>}
  </section>;
}
